Public Class Form1
    Private Sub listQuestNames_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ListQuestNames.SelectedIndexChanged
        zMatchListIndex(ListQuestNames, ListQuestIDs)
    End Sub

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        ListQuestNames.Items.Add("A Better Mousetrap")
        ListQuestNames.Items.Add("A Brotherhood Betrayed")
        ListQuestNames.Items.Add("A Brush with Death")
        ListQuestNames.Items.Add("A Door in Niben Bay")
        ListQuestNames.Items.Add("A Kiss Before Dying")
        ListQuestNames.Items.Add("A Knife in the Dark")
        ListQuestNames.Items.Add("A Liquid Solution")
        ListQuestNames.Items.Add("A Mage's Staff")
        ListQuestNames.Items.Add("A Matter of Honor")
        ListQuestNames.Items.Add("A Plot Revealed")
        ListQuestNames.Items.Add("A Rat Problem")
        ListQuestNames.Items.Add("A Shadow Over Hackdirt")
        ListQuestNames.Items.Add("A Venerable Vintage")
        ListQuestNames.Items.Add("A Watery Grave")
        ListQuestNames.Items.Add("Accidents Happen")
        ListQuestNames.Items.Add("Acrobatics Training")
        ListQuestNames.Items.Add("Addiction")
        ListQuestNames.Items.Add("Affairs of a Wizard")
        ListQuestNames.Items.Add("Ahdarji's Heirloom")
        ListQuestNames.Items.Add("Alchemy Acquisitions")
        ListQuestNames.Items.Add("Alchemy Training")
        ListQuestNames.Items.Add("Allies for Bruma")
        ListQuestNames.Items.Add("Alteration Training")
        ListQuestNames.Items.Add("Ambush")
        ListQuestNames.Items.Add("Amelion's Debt")
        ListQuestNames.Items.Add("An Unexpected Voyage")
        ListQuestNames.Items.Add("Anvil Recommendation")
        ListQuestNames.Items.Add("Arena")
        ListQuestNames.Items.Add("Armorer Training")
        ListQuestNames.Items.Add("Arrow of Extrication")
        ListQuestNames.Items.Add("Athletics Training")
        ListQuestNames.Items.Add("Attack on Fort Sutch")
        ListQuestNames.Items.Add("Azani Blackheart")
        ListQuestNames.Items.Add("Azura")
        ListQuestNames.Items.Add("Bad Medicine")
        ListQuestNames.Items.Add("Baiting the Trap")
        ListQuestNames.Items.Add("Battlehorn Castle")
        ListQuestNames.Items.Add("Bear Season")
        ListQuestNames.Items.Add("Blade Training")
        ListQuestNames.Items.Add("Block Training")
        ListQuestNames.Items.Add("Blood Price")
        ListQuestNames.Items.Add("Blood of the Daedra")
        ListQuestNames.Items.Add("Blood of the Damned")
        ListQuestNames.Items.Add("Blood of the Divines")
        ListQuestNames.Items.Add("Blunt Training")
        ListQuestNames.Items.Add("Boethia")
        ListQuestNames.Items.Add("Boots of Springheel Jak")
        ListQuestNames.Items.Add("Bravil Recommendation")
        ListQuestNames.Items.Add("Breaking the Siege of Kvatch")
        ListQuestNames.Items.Add("Brithaur")
        ListQuestNames.Items.Add("Broken Vows")
        ListQuestNames.Items.Add("Bruma Gate")
        ListQuestNames.Items.Add("Bruma Recommendation")
        ListQuestNames.Items.Add("Buy a house in Bravil")
        ListQuestNames.Items.Add("Buy a house in Cheydinhal")
        ListQuestNames.Items.Add("Buy a house in Leyawiin")
        ListQuestNames.Items.Add("Buy a house in the Imperial City")
        ListQuestNames.Items.Add("Buying a house in Skingrad")
        ListQuestNames.Items.Add("Canvas the Castle")
        ListQuestNames.Items.Add("Caught in the Hunt")
        ListQuestNames.Items.Add("Cheydinhal Recommendation")
        ListQuestNames.Items.Add("Clavicus Vile")
        ListQuestNames.Items.Add("Confront the King")
        ListQuestNames.Items.Add("Conjuration Training")
        ListQuestNames.Items.Add("Corruption and Conscience")
        ListQuestNames.Items.Add("Dagon Shrine")
        ListQuestNames.Items.Add("Darkness Eternal")
        ListQuestNames.Items.Add("Deepscorn Hollow")
        ListQuestNames.Items.Add("Defense of Bruma")
        ListQuestNames.Items.Add("Deliver the Amulet")
        ListQuestNames.Items.Add("Den of Thieves")
        ListQuestNames.Items.Add("Destruction Training")
        ListQuestNames.Items.Add("Drunk and Disorderly")
        ListQuestNames.Items.Add("Dunbarrow Cove")
        ListQuestNames.Items.Add("Enter the Eliminator")
        ListQuestNames.Items.Add("Everything In Its Place")
        ListQuestNames.Items.Add("Falling Awake")
        ListQuestNames.Items.Add("Final Justice")
        ListQuestNames.Items.Add("Final Resting")
        ListQuestNames.Items.Add("Find the Heir")
        ListQuestNames.Items.Add("Finding the Thieves Guild")
        ListQuestNames.Items.Add("Fingers of the Mountain")
        ListQuestNames.Items.Add("Fingers of the Mountain, Part II")
        ListQuestNames.Items.Add("Following a Lead")
        ListQuestNames.Items.Add("Frostcrag Spire")
        ListQuestNames.Items.Add("Ghosts of Vitharn")
        ListQuestNames.Items.Add("Go Fish")
        ListQuestNames.Items.Add("Goblin Trouble")
        ListQuestNames.Items.Add("Great Gate")
        ListQuestNames.Items.Add("Hand to Hand Training")
        ListQuestNames.Items.Add("Heavy Armor Training")
        ListQuestNames.Items.Add("Helping Hands")
        ListQuestNames.Items.Add("Hermaeus Mora")
        ListQuestNames.Items.Add("Hircine")
        ListQuestNames.Items.Add("Honor Thy Mother")
        ListQuestNames.Items.Add("Horse Armor")
        ListQuestNames.Items.Add("Illusion Training")
        ListQuestNames.Items.Add("Imperial Corruption ")
        ListQuestNames.Items.Add("Imperial Dragon Armor")
        ListQuestNames.Items.Add("Independent Thievery")
        ListQuestNames.Items.Add("Infiltration")
        ListQuestNames.Items.Add("Information Gathering")
        ListQuestNames.Items.Add("Information at a Price")
        ListQuestNames.Items.Add("Join the Mages Guild")
        ListQuestNames.Items.Add("Knights of the White Stallion")
        ListQuestNames.Items.Add("Legacy Lost")
        ListQuestNames.Items.Add("Leyawiin Recommendation")
        ListQuestNames.Items.Add("Liberation or Apprehension?")
        ListQuestNames.Items.Add("Lifting the Vale")
        ListQuestNames.Items.Add("Light Armor Training")
        ListQuestNames.Items.Add("Light the Dragonfires")
        ListQuestNames.Items.Add("Lost Histories")
        ListQuestNames.Items.Add("Malacath")
        ListQuestNames.Items.Add("Marksman Training")
        ListQuestNames.Items.Add("May the Best Thief Win")
        ListQuestNames.Items.Add("Mazoga the Orc")
        ListQuestNames.Items.Add("Mephala")
        ListQuestNames.Items.Add("Mercantile Training")
        ListQuestNames.Items.Add("Meridia")
        ListQuestNames.Items.Add("Miscarcand")
        ListQuestNames.Items.Add("Misdirection")
        ListQuestNames.Items.Add("Molag Bal")
        ListQuestNames.Items.Add("More Unfinished Business")
        ListQuestNames.Items.Add("My Brother's Keeper")
        ListQuestNames.Items.Add("Mystery at Harlun's Watch")
        ListQuestNames.Items.Add("Mysticism Training")
        ListQuestNames.Items.Add("Namira")
        ListQuestNames.Items.Add("Nature's Fury")
        ListQuestNames.Items.Add("Necromancer's Moon")
        ListQuestNames.Items.Add("Newheim's Flagon")
        ListQuestNames.Items.Add("Next of Kin")
        ListQuestNames.Items.Add("No Rest for the Wicked")
        ListQuestNames.Items.Add("No Stone Unturned")
        ListQuestNames.Items.Add("Nocturnal")
        ListQuestNames.Items.Add("Nothing You Can Possess")
        ListQuestNames.Items.Add("Of Secret And Shadow")
        ListQuestNames.Items.Add("Order of the Virtuous Blood")
        ListQuestNames.Items.Add("Origin of the Gray Prince")
        ListQuestNames.Items.Add("Paradise")
        ListQuestNames.Items.Add("Paranoia")
        ListQuestNames.Items.Add("Permanent Retirement")
        ListQuestNames.Items.Add("Peryite")
        ListQuestNames.Items.Add("Pilgrimage")
        ListQuestNames.Items.Add("Priory of the Nine")
        ListQuestNames.Items.Add("Raid on Greyland")
        ListQuestNames.Items.Add("Rebuilding the Gatekeeper")
        ListQuestNames.Items.Add("Repairing the Orrery")
        ListQuestNames.Items.Add("Restoration Training")
        ListQuestNames.Items.Add("Retaking The Fringe")
        ListQuestNames.Items.Add("Revenge Served Cold")
        ListQuestNames.Items.Add("Ritual of Accession")
        ListQuestNames.Items.Add("Ritual of Dementia")
        ListQuestNames.Items.Add("Ritual of Mania")
        ListQuestNames.Items.Add("Sanguine")
        ListQuestNames.Items.Add("Scheduled for Execution")
        ListQuestNames.Items.Add("Secrets of the Ayleids")
        ListQuestNames.Items.Add("Security Training")
        ListQuestNames.Items.Add("Seeking Your Roots")
        ListQuestNames.Items.Add("Separated at Birth")
        ListQuestNames.Items.Add("Sheogorath")
        ListQuestNames.Items.Add("Sins of the Father")
        ListQuestNames.Items.Add("Skingrad Recommendation")
        ListQuestNames.Items.Add("Sneak Training")
        ListQuestNames.Items.Add("Speechcraft Training")
        ListQuestNames.Items.Add("Spies")
        ListQuestNames.Items.Add("Stendarr's Mercy")
        ListQuestNames.Items.Add("Symbols of Office")
        ListQuestNames.Items.Add("Taking Care of Lex")
        ListQuestNames.Items.Add("Taxonomy of Obsession")
        ListQuestNames.Items.Add("Tears of the Savior")
        ListQuestNames.Items.Add("The Antipodean Hammer")
        ListQuestNames.Items.Add("The Assassin's Gambit")
        ListQuestNames.Items.Add("The Assassinated Man")
        ListQuestNames.Items.Add("The Battle for Castle Kvatch")
        ListQuestNames.Items.Add("The Blessing of Talos")
        ListQuestNames.Items.Add("The Bloodworm Helm")
        ListQuestNames.Items.Add("The Cold Flame of Agnon")
        ListQuestNames.Items.Add("The Coldest Sleep")
        ListQuestNames.Items.Add("The Collector")
        ListQuestNames.Items.Add("The Coming Storm")
        ListQuestNames.Items.Add("The Dead Drop")
        ListQuestNames.Items.Add("The Desolate Mine")
        ListQuestNames.Items.Add("The Elven Maiden")
        ListQuestNames.Items.Add("The End of Order")
        ListQuestNames.Items.Add("The Faithful Squire")
        ListQuestNames.Items.Add("The Fork of Horripilation")
        ListQuestNames.Items.Add("The Forlorn Watchman")
        ListQuestNames.Items.Add("The Fugitives")
        ListQuestNames.Items.Add("The Ghost Ship of Anvil")
        ListQuestNames.Items.Add("The Gravefinder's Repose")
        ListQuestNames.Items.Add("The Great Divide")
        ListQuestNames.Items.Add("The Helpless Army")
        ListQuestNames.Items.Add("The Hist")
        ListQuestNames.Items.Add("The Killing Field")
        ListQuestNames.Items.Add("The Lady of Paranoia")
        ListQuestNames.Items.Add("The Lonely Wanderer")
        ListQuestNames.Items.Add("The Master's Son")
        ListQuestNames.Items.Add("The Museum of Oddities")
        ListQuestNames.Items.Add("The Necromancer's Amulet")
        ListQuestNames.Items.Add("The Night Mother's Child")
        ListQuestNames.Items.Add("The Noble's Daughter")
        ListQuestNames.Items.Add("The Path of Dawn")
        ListQuestNames.Items.Add("The Path of the Righteous")
        ListQuestNames.Items.Add("The Potato Snatcher")
        ListQuestNames.Items.Add("The Prince of Madness")
        ListQuestNames.Items.Add("The Purification")
        ListQuestNames.Items.Add("The Renegade Shadowscale")
        ListQuestNames.Items.Add("The Roots of Madness")
        ListQuestNames.Items.Add("The Rosethorn Cache")
        ListQuestNames.Items.Add("The Shrine of the Crusader")
        ListQuestNames.Items.Add("The Siren's Deception")
        ListQuestNames.Items.Add("The Stone of St. Alessia")
        ListQuestNames.Items.Add("The Sunken One")
        ListQuestNames.Items.Add("The Sword of the Crusader")
        ListQuestNames.Items.Add("The Ultimate Heist")
        ListQuestNames.Items.Add("The Unfortunate Shopkeeper")
        ListQuestNames.Items.Add("The Wandering Scholar")
        ListQuestNames.Items.Add("The Wayward Knight")
        ListQuestNames.Items.Add("Through A Nightmare, Darkly")
        ListQuestNames.Items.Add("Through the Fringe of Madness")
        ListQuestNames.Items.Add("To Help A Hero")
        ListQuestNames.Items.Add("To Serve Sithis")
        ListQuestNames.Items.Add("Trolls of Forsaken Mine")
        ListQuestNames.Items.Add("Turning a Blind Eye")
        ListQuestNames.Items.Add("Tutorial")
        ListQuestNames.Items.Add("Two Sides of the Coin")
        ListQuestNames.Items.Add("Ulterior Motives")
        ListQuestNames.Items.Add("Umaril the Unfeathered")
        ListQuestNames.Items.Add("Understanding Madness")
        ListQuestNames.Items.Add("Unearthing Mehrunes Razor")
        ListQuestNames.Items.Add("Unfinished Business")
        ListQuestNames.Items.Add("Unfriendly Competition")
        ListQuestNames.Items.Add("Untaxing the Poor")
        ListQuestNames.Items.Add("Ushnar's Terror")
        ListQuestNames.Items.Add("Vaermina")
        ListQuestNames.Items.Add("Vahtacen's Secret")
        ListQuestNames.Items.Add("Vampire Cure")
        ListQuestNames.Items.Add("Welcome to the Family")
        ListQuestNames.Items.Add("Weynon Priory")
        ListQuestNames.Items.Add("When the Vow Breaks")
        ListQuestNames.Items.Add("Where Spirits Have Lease")
        ListQuestNames.Items.Add("Whispers of Death")
        ListQuestNames.Items.Add("Whodunit?")
        ListQuestNames.Items.Add("Whom Gods Annoy")
        ListQuestNames.Items.Add("Wisdom of the Ages")
        ListQuestNames.Items.Add("Work is Never Done")
        ListQuestNames.Items.Add("Zero Visibility")

        ListQuestIDs.Items.Add("SE03")
        ListQuestIDs.Items.Add("MS11")
        ListQuestIDs.Items.Add("MS14")
        ListQuestIDs.Items.Add("SE01Door")
        ListQuestIDs.Items.Add("Dark16Kiss")
        ListQuestIDs.Items.Add("Dark01Knife")
        ListQuestIDs.Items.Add("SE41")
        ListQuestIDs.Items.Add("MG08MagesStaff")
        ListQuestIDs.Items.Add("Dark14Honor")
        ListQuestIDs.Items.Add("MG14Plot")
        ListQuestIDs.Items.Add("FGC01Rats")
        ListQuestIDs.Items.Add("MS45")
        ListQuestIDs.Items.Add("SQ08")
        ListQuestIDs.Items.Add("Dark02Watery")
        ListQuestIDs.Items.Add("Dark03Accidents")
        ListQuestIDs.Items.Add("TrainingAcrobatics")
        ListQuestIDs.Items.Add("SE04")
        ListQuestIDs.Items.Add("Dark10SpecialWizard")
        ListQuestIDs.Items.Add("TG04Mistake")
        ListQuestIDs.Items.Add("MG19Alchemy")
        ListQuestIDs.Items.Add("TrainingAlchemy")
        ListQuestIDs.Items.Add("MQ11")
        ListQuestIDs.Items.Add("TrainingAlteration")
        ListQuestIDs.Items.Add("MG17Ambush")
        ListQuestIDs.Items.Add("FGC07Heirloom")
        ListQuestIDs.Items.Add("MS31")
        ListQuestIDs.Items.Add("MG04Restore")
        ListQuestIDs.Items.Add("ArenaDialogue")
        ListQuestIDs.Items.Add("TrainingArmorer")
        ListQuestIDs.Items.Add("TG09Arrow")
        ListQuestIDs.Items.Add("TrainingAthletics")
        ListQuestIDs.Items.Add("MS94")
        ListQuestIDs.Items.Add("FGD05Oreyn")
        ListQuestIDs.Items.Add("DAAzura")
        ListQuestIDs.Items.Add("Dark07Medicine")
        ListQuestIDs.Items.Add("SE03A")
        ListQuestIDs.Items.Add("DLCBattlehornCastle")
        ListQuestIDs.Items.Add("SQ06")
        ListQuestIDs.Items.Add("TrainingBlade")
        ListQuestIDs.Items.Add("TrainingBlock")
        ListQuestIDs.Items.Add("TG04BloodPrice")
        ListQuestIDs.Items.Add("MQ08")
        ListQuestIDs.Items.Add("Dark02WateryFIN")
        ListQuestIDs.Items.Add("MQ09")
        ListQuestIDs.Items.Add("TrainingBlunt")
        ListQuestIDs.Items.Add("DABoethia")
        ListQuestIDs.Items.Add("TG10Boots")
        ListQuestIDs.Items.Add("MG03Illusion")
        ListQuestIDs.Items.Add("MS48")
        ListQuestIDs.Items.Add("SE35")
        ListQuestIDs.Items.Add("Dark12Harem")
        ListQuestIDs.Items.Add("MQ10")
        ListQuestIDs.Items.Add("MG06Bruma")
        ListQuestIDs.Items.Add("HouseBravil")
        ListQuestIDs.Items.Add("HouseCheydinhal")
        ListQuestIDs.Items.Add("HouseLeyawiin")
        ListQuestIDs.Items.Add("HouseImperialCity")
        ListQuestIDs.Items.Add("HouseSkingrad")
        ListQuestIDs.Items.Add("MS51")
        ListQuestIDs.Items.Add("MS08")
        ListQuestIDs.Items.Add("MG02Alter")
        ListQuestIDs.Items.Add("DAClavicusVile")
        ListQuestIDs.Items.Add("MG18KingofWorms")
        ListQuestIDs.Items.Add("TrainingConjuration")
        ListQuestIDs.Items.Add("MS10")
        ListQuestIDs.Items.Add("MQ06")
        ListQuestIDs.Items.Add("DarkVamp")
        ListQuestIDs.Items.Add("DLCDeepscorn")
        ListQuestIDs.Items.Add("MQ13")
        ListQuestIDs.Items.Add("MQ02")
        ListQuestIDs.Items.Add("FGC03Thieves")
        ListQuestIDs.Items.Add("TrainingDestruction")
        ListQuestIDs.Items.Add("FGD02DandD")
        ListQuestIDs.Items.Add("DLC06ThievesDen")
        ListQuestIDs.Items.Add("Dark06WandererFIN")
        ListQuestIDs.Items.Add("SE39")
        ListQuestIDs.Items.Add("SE40")
        ListQuestIDs.Items.Add("Dark13Justice")
        ListQuestIDs.Items.Add("SE36")
        ListQuestIDs.Items.Add("MQ03")
        ListQuestIDs.Items.Add("TG00FindThievesGuild")
        ListQuestIDs.Items.Add("MG05Fingers")
        ListQuestIDs.Items.Add("MG05A")
        ListQuestIDs.Items.Add("Dark17Following")
        ListQuestIDs.Items.Add("DLCFrostcragSpire")
        ListQuestIDs.Items.Add("SE32")
        ListQuestIDs.Items.Add("SQ09")
        ListQuestIDs.Items.Add("MS46")
        ListQuestIDs.Items.Add("MQ14")
        ListQuestIDs.Items.Add("TrainingHandtoHand")
        ListQuestIDs.Items.Add("TrainingHeavyArmor")
        ListQuestIDs.Items.Add("HouseServant")
        ListQuestIDs.Items.Add("DAHermaeusMora")
        ListQuestIDs.Items.Add("DAHircine")
        ListQuestIDs.Items.Add("Dark18Mother")
        ListQuestIDs.Items.Add("DLCHorseArmor")
        ListQuestIDs.Items.Add("TrainingIllusion")
        ListQuestIDs.Items.Add("MS26 ")
        ListQuestIDs.Items.Add("MQDragonArmor")
        ListQuestIDs.Items.Add("TGStolenGoods")
        ListQuestIDs.Items.Add("FGD08Infiltration")
        ListQuestIDs.Items.Add("FGD07Kidnap")
        ListQuestIDs.Items.Add("MG13Information")
        ListQuestIDs.Items.Add("MG00Join")
        ListQuestIDs.Items.Add("MS92")
        ListQuestIDs.Items.Add("MS16A")
        ListQuestIDs.Items.Add("MG07Leyawiin")
        ListQuestIDs.Items.Add("MG12Gate")
        ListQuestIDs.Items.Add("MS12")
        ListQuestIDs.Items.Add("TrainingLightArmor")
        ListQuestIDs.Items.Add("MQ16")
        ListQuestIDs.Items.Add("TG06Atonement")
        ListQuestIDs.Items.Add("DAMalacath")
        ListQuestIDs.Items.Add("TrainingMarksman")
        ListQuestIDs.Items.Add("TG01BestThief")
        ListQuestIDs.Items.Add("MS91")
        ListQuestIDs.Items.Add("DAMephala")
        ListQuestIDs.Items.Add("TrainingMercantile")
        ListQuestIDs.Items.Add("DAMeridia")
        ListQuestIDs.Items.Add("MQ12")
        ListQuestIDs.Items.Add("TG05Misdirection")
        ListQuestIDs.Items.Add("DAMolagBal")
        ListQuestIDs.Items.Add("FGD04Defector")
        ListQuestIDs.Items.Add("Dark05AssassinatedFIN")
        ListQuestIDs.Items.Add("FGC10Swamp")
        ListQuestIDs.Items.Add("TrainingMysticism")
        ListQuestIDs.Items.Add("DANamira")
        ListQuestIDs.Items.Add("ND03")
        ListQuestIDs.Items.Add("MG11NecroMoon")
        ListQuestIDs.Items.Add("FGC03Flagon")
        ListQuestIDs.Items.Add("Dark11Kin")
        ListQuestIDs.Items.Add("Dark03AccidentsFIN")
        ListQuestIDs.Items.Add("SQ04")
        ListQuestIDs.Items.Add("DANocturnal")
        ListQuestIDs.Items.Add("MS22")
        ListQuestIDs.Items.Add("Dark09RetirementFIN")
        ListQuestIDs.Items.Add("MS23")
        ListQuestIDs.Items.Add("MS52")
        ListQuestIDs.Items.Add("MQ15")
        ListQuestIDs.Items.Add("MS38")
        ListQuestIDs.Items.Add("Dark09Retirement")
        ListQuestIDs.Items.Add("DAPeryite")
        ListQuestIDs.Items.Add("NDPilgrim")
        ListQuestIDs.Items.Add("ND02")
        ListQuestIDs.Items.Add("SQ02")
        ListQuestIDs.Items.Add("SE09")
        ListQuestIDs.Items.Add("DLCOrrery")
        ListQuestIDs.Items.Add("TrainingRestoration")
        ListQuestIDs.Items.Add("SE08")
        ListQuestIDs.Items.Add("SQ03")
        ListQuestIDs.Items.Add("SE07")
        ListQuestIDs.Items.Add("SE07A")
        ListQuestIDs.Items.Add("SE07B")
        ListQuestIDs.Items.Add("DASanguine")
        ListQuestIDs.Items.Add("Dark04Execution")
        ListQuestIDs.Items.Add("MS27")
        ListQuestIDs.Items.Add("TrainingSecurity")
        ListQuestIDs.Items.Add("MS39")
        ListQuestIDs.Items.Add("MS16")
        ListQuestIDs.Items.Add("DASheogorath")
        ListQuestIDs.Items.Add("MS16B")
        ListQuestIDs.Items.Add("MG01Destruct")
        ListQuestIDs.Items.Add("TrainingSneak")
        ListQuestIDs.Items.Add("TrainingSpeechcraft")
        ListQuestIDs.Items.Add("MQ07")
        ListQuestIDs.Items.Add("ND06")
        ListQuestIDs.Items.Add("SE11")
        ListQuestIDs.Items.Add("TG07Lex")
        ListQuestIDs.Items.Add("SE37")
        ListQuestIDs.Items.Add("MS37")
        ListQuestIDs.Items.Add("SE30")
        ListQuestIDs.Items.Add("Dark08WhodunitFIN")
        ListQuestIDs.Items.Add("Dark05Assassinated")
        ListQuestIDs.Items.Add("MS49")
        ListQuestIDs.Items.Add("ND09")
        ListQuestIDs.Items.Add("MG15Helm")
        ListQuestIDs.Items.Add("SE06")
        ListQuestIDs.Items.Add("Dark15Coldest")
        ListQuestIDs.Items.Add("MS21")
        ListQuestIDs.Items.Add("SE44")
        ListQuestIDs.Items.Add("Dark10SanctuaryFIN")
        ListQuestIDs.Items.Add("FGC06Courier")
        ListQuestIDs.Items.Add("TG03Elven")
        ListQuestIDs.Items.Add("SE13")
        ListQuestIDs.Items.Add("ND07")
        ListQuestIDs.Items.Add("SE45")
        ListQuestIDs.Items.Add("MS06")
        ListQuestIDs.Items.Add("FGC08Prison")
        ListQuestIDs.Items.Add("MS93")
        ListQuestIDs.Items.Add("SQ05")
        ListQuestIDs.Items.Add("SE46")
        ListQuestIDs.Items.Add("SE10")
        ListQuestIDs.Items.Add("FGD09Hist")
        ListQuestIDs.Items.Add("MS18")
        ListQuestIDs.Items.Add("SE05")
        ListQuestIDs.Items.Add("Dark06Wanderer")
        ListQuestIDs.Items.Add("FGD03Viranus")
        ListQuestIDs.Items.Add("SE38")
        ListQuestIDs.Items.Add("MG16Amulet")
        ListQuestIDs.Items.Add("Dark07MedicineFIN")
        ListQuestIDs.Items.Add("FGC09Ogres")
        ListQuestIDs.Items.Add("MQ05")
        ListQuestIDs.Items.Add("ND04")
        ListQuestIDs.Items.Add("SQ01")
        ListQuestIDs.Items.Add("SE14")
        ListQuestIDs.Items.Add("Dark10Sanctuary")
        ListQuestIDs.Items.Add("MSShadowscale")
        ListQuestIDs.Items.Add("SE12")
        ListQuestIDs.Items.Add("HouseSkingradQuest")
        ListQuestIDs.Items.Add("ND01")
        ListQuestIDs.Items.Add("MS04")
        ListQuestIDs.Items.Add("FGC05Stone")
        ListQuestIDs.Items.Add("SQ07")
        ListQuestIDs.Items.Add("ND08")
        ListQuestIDs.Items.Add("TG11Heist")
        ListQuestIDs.Items.Add("FGC02Protect")
        ListQuestIDs.Items.Add("FGC04Scholar")
        ListQuestIDs.Items.Add("MS13")
        ListQuestIDs.Items.Add("MS05")
        ListQuestIDs.Items.Add("SE02")
        ListQuestIDs.Items.Add("SE34")
        ListQuestIDs.Items.Add("Dark04ExecutionFIN")
        ListQuestIDs.Items.Add("FGD06DeadViranus")
        ListQuestIDs.Items.Add("TG08Blind")
        ListQuestIDs.Items.Add("MQ01")
        ListQuestIDs.Items.Add("MS09")
        ListQuestIDs.Items.Add("MG09Motives")
        ListQuestIDs.Items.Add("ND10")
        ListQuestIDs.Items.Add("SE04Shell")
        ListQuestIDs.Items.Add("DL9MehrunesQuest")
        ListQuestIDs.Items.Add("FGD01Default")
        ListQuestIDs.Items.Add("MS29")
        ListQuestIDs.Items.Add("TG02taxes")
        ListQuestIDs.Items.Add("SE43")
        ListQuestIDs.Items.Add("DAVaermina")
        ListQuestIDs.Items.Add("MG10Vahtacen")
        ListQuestIDs.Items.Add("MS40")
        ListQuestIDs.Items.Add("Dark01KnifeFIN")
        ListQuestIDs.Items.Add("MQ04")
        ListQuestIDs.Items.Add("SQ10")
        ListQuestIDs.Items.Add("MS02")
        ListQuestIDs.Items.Add("Dark19Whispers")
        ListQuestIDs.Items.Add("Dark08Whodunit")
        ListQuestIDs.Items.Add("MS43")
        ListQuestIDs.Items.Add("ND05")
        ListQuestIDs.Items.Add("SE42")
        ListQuestIDs.Items.Add("MS47")

    End Sub

    Private Sub ListQuestIDs_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ListQuestIDs.SelectedIndexChanged
        zMatchListIndex(ListQuestIDs, ListQuestNames)
    End Sub

    Private Sub btAdd_Click(sender As Object, e As EventArgs) Handles btAdd.Click
        zTextLinesToListbox(txtInput, ListCompareInput, 1)
    End Sub

    Private Sub btGenListWithNames_Click(sender As Object, e As EventArgs) Handles btGenListWithNames.Click
        If ListCompareInput.Items.Count = 0 Then Exit Sub
        Dim zTi As Integer
        Dim zTi2 As Integer
        Dim zTempOutstr As String
        For zTi = 0 To ListCompareInput.Items.Count - 1
            Application.DoEvents()
            For zTi2 = 0 To ListQuestIDs.Items.Count - 1
                Application.DoEvents()
                If ListCompareInput.Items.Item(zTi) = ListQuestIDs.Items.Item(zTi2) Then
                    zTempOutstr = zTempOutstr & ListQuestNames.Items.Item(zTi2) & " - " & ListCompareInput.Items.Item(zTi) & zR
                End If
            Next
        Next
        txtCompareOutput.Text = zTempOutstr
    End Sub

    Private Sub btClear_Click(sender As Object, e As EventArgs) Handles btClear.Click
        txtInput.Text = ""
    End Sub
End Class
