"Resource/UI/HealthIconPanel.res"
{
	"HealthIcon"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"HealthIcon"
		"xpos"			"0"
		//"xpos"			"10"
		"xpos_minmode"	"0"
		"ypos"			"0"
		//"ypos"			"-200"
		"ypos_minmode"	"0"
		//"wide"			"32"
		//"tall"			"32"
		"wide"			"64"
		"tall"			"64"
		"visible"		"1"
		"enabled"		"1"	
		"TFFont"		"HudFontSmall"
		"TextColor"		"HudOffWhite"
		"autoResize"	"1"
	}
	"SpectatorGUIHealth"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"SpectatorGUIHealth"
		//"xpos"			"0"
		"xpos"			"10"
		"xpos_minmode"	"0"
		//"ypos"			"0"
		"ypos"			"20"
		"ypos_minmode"	"0"
		"wide"			"128"
		"tall"			"128"
		"visible"		"1"
		"enabled"		"1"	
		"TFFont"		"HudFontSmall"
		"TextColor"		"HudOffWhite"
		"autoResize"	"1"
	}	
}
